# This is a basic workflow to help you get started with Actions

name: Build-Host

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - '*'
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Copy dlls to host folder
        run: cp sdk/windows/* examples/host

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      
      # Build the host app
      - name: Build host
        continue-on-error: true
        run: |
          cd examples/host
          nmake help
          nmake -h
          nmake --help
          nmake
          nmake all
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: host-build
          path: examples/host
